version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: learning-api
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker-data:/var/lib/mysql
    ports:
      - 3308:3306